### ISSUE TITLE
Plugin is non-functional 

### ISSUE THREAD

**Issue by mitcht** [artf/grapesjs-custom-code#11]
Upon clone, and execute index.html to view the demo, a few javascript errors are displayed.

Failed to load resource: grapesjs-plugin-boilerplate.min.js

and

Plugin grapesjs-custom-code not found.

**Comment by mitcht** [comment]
Looks like adding a reference to it helps.  Not sure whats up with boilerplate / missing files, but adding 

`<script src="dist/grapesjs-custom-code.min.js"></script>`

to the <HEAD> in index.html fixes things.

**Comment by theSC0RP** [comment]
This solved the error of plugin not found:
`import customCodePlugin from 'grapesjs-custom-code';`

and you can add it in plugins as follows:
```
const editor = grapesjs.init({
  // ...
  plugins: [customCodePlugin]
  // ...
})
```
