### ISSUE TITLE
Why <script> cannot be used?

### ISSUE THREAD

**Issue by xinnai** [artf/grapesjs-custom-code#14]
I want to learn how to set Js to the canvas so I download this source code . And I found the code :
`// Avoid rendering codes with scripts
                    if (content.indexOf('<script') >= 0) {
                        this.el.innerHTML = opts.placeholderScript;
                        droppable = 0;
                    }`

But why can't I set js custom code? I try to comment out your above code and set code like 
`<div id="aaa"></div><style>
  #aaa{
  	width: 200px;
    height: 200px;
    
  }</style>
<script>
document.getElementById("aaa").style.background = "red"
</script>
`

The js code just not work, can I set js code for the whole canvas(not only one element or component)? I tryed to do that using `setComponents` but it also don't  work

`const htmlValue = this.htmlEditor.getValue();
  const jsValue = this.jsEditor.getValue();
  let newHtml = htmlValue + "<script>" + jsValue + "<" + "/script>";
 
  this.editor.setComponents(newHtml)
`
Can you help me how to set js code ? Thank you very much!!!

**Comment by tomaskallup** [comment]
The reason is simple, your script won't render inside the editor (because it could break the editor). It will however render in the result, so if you redner the HTML from editor, it will work.
