### ISSUE TITLE
Plugin fails to load with no setter error

### ISSUE THREAD

**Issue by TheDude70** [artf/grapesjs-custom-code#21]
adding this plugin to Grapesjs causes the editor to fail loading with console error:
`Cannot set property defaults of #<n> which has only a getter`

We're running Grapejs in a Vue component, but even declaring the editor outside of Vue results in same issue.

Have also tried both ways to import the plugin with same result.

Currently am running 0.20.1 as the Grapesjs version

**Comment by artf** [comment]
I see no issues with this plugin as it's used also on the official demo.
The latest version of grapesjs https://github.com/artf/grapesjs/releases/tag/v0.20.1 introduces a change which might generate that error if there is an usage of the legacy API for custom components (which is not a case of this plugin).
Ensure you're not using that legacy API in your custom components or maybe some other plugin.

A reproducible demo might be helpful in such a case.

**Comment by TheDude70** [comment]
@artf not sure why this is immediately closed 🤔 

I am experiencing this when this plugin is added to the `plugins` grapejs.init options. My init below. all other plugins including my custom ones work fine with 0.20.1. Only when I 'enable' custom-code does it throw error. So if there somehow would be an issue with legacy API, then why just this plugin that causes an issue?

`this.editor = grapesjs.init({
      container: '#gjs',
      width: 'auto',
      noticeOnUnload: 0,
      allowScripts: 1,
      components: this.landing_page.components || this.landing_page.html,
      style: this.landing_page.style || this.landing_page.css,
      storageManager: {
        type: null
      },
      styleManager: {
        clearProperties: 1,
      },
      fromElement: false,
      assetManager: {
        storageType: '',
        storeOnChange: true,
        storeAfterUpload: true,
        assets: [],
        uploadFile: this.uploadImage,
      },
      plugins: ['gjs-preset-webpage', 'grapesjs-plugin-forms', grapesjsImage, grapesjsLink], //'grapesjs-custom-code' 9/16/2022 broken
      pluginsOpts: {
        'gjs-preset-webpage': {
          blocks: ['quote'],
          blocksBasicOpts: {
            blocks: ['image',
              'video']
          },
          navbarOpts: false,
          countdownOpts: false,
          formsOpts: false,
          customStyleManager: [],
        },
        /*'grapesjs-custom-code': {
          blockCustomCode: {
            category: 'Extras',
          }
        },*/
        'grapesjs-plugin-forms': {
          blocks: ['form', 'label']
        }`

**Comment by TheDude70** [comment]
Have disabled all other plugins and just have the custom-code plugin and still same issue.  Removing the plugin solves the error.

My custom components do not use legacy API.

**Comment by TheDude70** [comment]
@artf I removed the plugin and reinstalled it and now it is working. Apparently something did not work right with update from 0.1.3 to 1.0.1, so blame it on npm 😛
