### ISSUE TITLE
Drag and drop of custom code second time it's not working

### ISSUE THREAD

**Issue by Saravanakumar46** [artf/grapesjs-custom-code#4]
When I drag and drop custom code 1st time it's working fine, on 2nd time when I drag and drop it's not working It's just shows 'Insert here your custom code' as text. 

![image](https://user-images.githubusercontent.com/12663124/55081395-cecf9200-50c5-11e9-8e82-1fa83a2cfdba.png)

**Comment by hitaloramon** [comment]
@artf I'm also having this same problem.

**Comment by trafalmejo** [comment]
Also facing the same problem

**Comment by HelveticaScenario** [comment]
same problem

**Comment by HelveticaScenario** [comment]
I've found that adding 
```
editor.on('run:custom-code:open-modal', () =>
  editor.once('modal:close', () => {
    const { Commands } = editor;
    if (Commands.isActive('custom-code:open-modal')) {
      Commands.stop('custom-code:open-modal');
    }
  }),
);
```
fixes the bug

**Comment by trafalmejo** [comment]
@HelveticaScenario you just made my day. Thanks.
This same issue happens with the import modal. I changed the command "custom-code:open-modal" by "gjs-open-import-webpage", and this fixes that event as well.

**Comment by Saravanakumar46** [comment]
It's working :dancer: 
Thanks @HelveticaScenario

**Comment by artf** [comment]
Should be fixed in https://github.com/artf/grapesjs-custom-code/releases/tag/v0.1.2
