### ISSUE TITLE
[Question] Editing a code block after loading a saved HTML

### ISSUE THREAD

**Issue by onshiryuu** [artf/grapesjs-custom-code#5]
Is it possible to enable/implement the editing of a custom code block, after the HTML has been saved in the database, and reloaded into the editor?

Because when saving the HTML currently the custom code block loses all reference of it being a custom code block and is just saved as a simple div.

Is there a way to mark this div as a custom code block when exporting the HTML via editor.getHtml(), so that grapesjs will recognize it as a custom code block when the HTML is loaded via editor.addComponents() ?

Thank you.

**Comment by artf** [comment]
Try with this
```js
const dc = editor.DomComponents;
const ccM = dc.getType('custom-code').model;
dc.addType('custom-code', {
	model: {
		getAttrToHTML() {
			const attrs = ccM.prototype.getAttrToHTML.apply(this, arguments);
			attrs['data-gjs-type'] = 'custom-code'; // Force the type in HTML
			return attrs;
		}
	}
});
```
https://jsfiddle.net/artur_arseniev/tLs6581u

**Comment by viveks1422** [comment]
I'm getting the same issue after saving data to HTML.  I'm unable to see custom code edit icon and that code block turned into just text.
