### ISSUE TITLE
Once saved and reloaded, it is no longer recognized as a component custom-code type.

### ISSUE THREAD

**Issue by chiqui3d** [artf/grapesjs-custom-code#9]
Once saved and reloaded, it is no longer recognized as a component `custom-code` type, but rather as a text component

**Comment by edwinjoel1984** [comment]
> Once saved and reloaded, it is no longer recognized as a component `custom-code` type, but rather as a text component

same problem

**Comment by aprendizfc** [comment]
@chiqui3d, did you solve the issue? I'm having the same problem

**Comment by chiqui3d** [comment]
I honestly don't remember why I closed this. I'll check the Editor to see if I made any modifications or finally left as it is.

**Comment by viveks1422** [comment]
The problem still exist
